[build]
  base    = "ClassRPG"
  command = "npm run build"
  publish = "ClassRPG/dist"
 
[build.environment]
  NODE_VERSION = "20"
 
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
