/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherManageRouteImport } from './routes/teacher.manage'
import { Route as CombatMissionIdRouteImport } from './routes/combat.$missionId'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherManageRoute = TeacherManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => TeacherRoute,
} as any)
const CombatMissionIdRoute = CombatMissionIdRouteImport.update({
  id: '/combat/$missionId',
  path: '/combat/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teams': typeof TeamsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/combat/$missionId': typeof CombatMissionIdRoute
  '/teacher/manage': typeof TeacherManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teams': typeof TeamsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/combat/$missionId': typeof CombatMissionIdRoute
  '/teacher/manage': typeof TeacherManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/teams': typeof TeamsRoute
  '/activity/$id': typeof ActivityIdRoute
  '/combat/$missionId': typeof CombatMissionIdRoute
  '/teacher/manage': typeof TeacherManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/missions'
    | '/notifications'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/student'
    | '/teacher'
    | '/teams'
    | '/activity/$id'
    | '/combat/$missionId'
    | '/teacher/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/missions'
    | '/notifications'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/student'
    | '/teacher'
    | '/teams'
    | '/activity/$id'
    | '/combat/$missionId'
    | '/teacher/manage'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/activities'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/missions'
    | '/notifications'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/student'
    | '/teacher'
    | '/teams'
    | '/activity/$id'
    | '/combat/$missionId'
    | '/teacher/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MissionsRoute: typeof MissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  RankingRoute: typeof RankingRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  ActivityIdRoute: typeof ActivityIdRoute
  CombatMissionIdRoute: typeof CombatMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/manage': {
      id: '/teacher/manage'
      path: '/manage'
      fullPath: '/teacher/manage'
      preLoaderRoute: typeof TeacherManageRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/combat/$missionId': {
      id: '/combat/$missionId'
      path: '/combat/$missionId'
      fullPath: '/combat/$missionId'
      preLoaderRoute: typeof CombatMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeacherRouteChildren {
  TeacherManageRoute: typeof TeacherManageRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherManageRoute: TeacherManageRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MissionsRoute: MissionsRoute,
  NotificationsRoute: NotificationsRoute,
  RankingRoute: RankingRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRouteWithChildren,
  TeamsRoute: TeamsRoute,
  ActivityIdRoute: ActivityIdRoute,
  CombatMissionIdRoute: CombatMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
